import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/(navbar)/Navbar";
import Footer from "./components/(footer)/Footer";
// import localFont from 'next/font/local';

// const heroFont = localFont({
//   src: [
//     {
//       path: "../../public/fonts/font2.woff2",
//       weight: "900",
//       style: "normal",
//     }
//   ],
//       variable: "--font-hero",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Navbar/>
        {children}
      <Footer/>
      </body>
    </html>
  );
}
